package com.riftforge.rules;

public enum LegalAction {
  KEEP_HAND,
  MULLIGAN,
  PASS_PHASE,
  END_TURN,
  PLAY_CARD,
  MOVE_TO_BATTLEFIELD,
  REPOSITION_CARD,
  RESOLVE_SHOWDOWN,
  TAP_RUNE,
  DISCARD_RUNE,
  UNDO_RUNES,
  VISION_CHOICE,
  HIDE_CARD,
  EQUIP_GEAR,
  SANDBOX_DEAL_CARD,
  SANDBOX_ADJUST_SCORE,
  SANDBOX_TAP_CARD,
  SANDBOX_FLIP_CARD,
  SANDBOX_MOVE_CARD
}
